'use client';
import { Roboto, Nunito } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import QueryProvider from "@/providers/QueryProvider";
import { usePathname } from "next/navigation";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Clone like save.co",
//   description: "Generated by next js",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();
  const isDashboard = pathname.includes("/dashboard");
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${nunito.variable} antialiased`}
      >
        <QueryProvider>
          {!isDashboard && <Header />}
          <main className="">
              {children}
          </main>
          <Footer />
        </QueryProvider>
      </body>
    </html>
  );
}
